### ISSUE TITLE
假设所有机器都重启，最近一次达成的决议会不会丢失？

### ISSUE THREAD

**Issue by pecywang** [Tencent/phxpaxos#100]
看到实例重启时有如下代码，即每次重启只学习到PaxosLog中倒数第二条InstanceId的log
int Instance :: PlayLog(const uint64_t llBeginInstanceID, const uint64_t llEndInstanceID) 
{
    for (uint64_t llInstanceID = llBeginInstanceID; llInstanceID < llEndInstanceID; llInstanceID++) {
        // Replay PaxosLog
    }
}
那么，假设一个集群有ABC三台机器（在同一机房），正常流程达成一轮决议后，机房突然停电了，ABC无一幸免，那么当ABC三台机器各自重启后，都加载不到最近达成的决议，不能重放到状态机，那么这个已经达成的决议是不是会丢失？但是已经告诉client成功了，丢失是肯定不能接受的

**Comment by unixliang** [comment]
假设llEndInstanceID的提议是chosen的，这里有两种办法保证线性一致读：
1. 待master选出来后读master，master选举成功前llEndInstanceID的提议会apply到状态机；
2. 如果不需要master，那需要做一次paxos决议才能读最新数据，这和方法1类似。
