### ISSUE TITLE
一下场景是否会有丢失数据的风险？

### ISSUE THREAD

**Issue by pecywang** [Tencent/phxpaxos#101]
假设一种场景：ABC三台机器组成的集群，ABC当前InstanceId均为2，A发起了Propose只得到了B的响应（C暂时失联），AB满足多数派，所以A发起了ProposerSendSuccess消息，B的Learner接收到了此消息，并且Apply到了状态机，B的InstanceId+1=3，但A的Learner在刚接收到ProposerSendSuccess消息时，机器突然挂了，那么A重启后InstanceId还是2，C此时回来了，当前B的InstanceId=3，AC的InstanceId=2,。

有如下几种情况：
1.网络正常，AC学习到B的InstanceId=3的值，ABC数据对齐；
2.AC和B网络Partition，新的client请求到A，AC在InstanceId=2达成了多数派，AC各自InstanceId+1=3；

对于第2中情况，网络全部恢复后，在ABC各自的Learner互相学习之前，ABC都达到了InstanceId=3，但B的数据和AC是不一样的（B的ProposalId小，Value也不同），那么此时如果B接收了Client的一个新请求，发起了新的Propose，在如下代码：
int Instance :: OnReceivePaxosMsg(const PaxosMsg & oPaxosMsg, const bool bIsRetry)
{
    // ...
    ChecksumLogic(oPaxosMsg);
    return ReceiveMsgForAcceptor(oPaxosMsg, bIsRetry);
}
有ChecksumLogic，此函数检查了InstanceId必须要相等，而且有
assert(oPaxosMsg.lastchecksum() == GetLastChecksum());
那么对于AC，checksum会和B发来的不一致，那AC就会挂掉，AC挂掉重启后，又只能Replay到InstanceId=2的PaxosLog，InstanceId=3的要向B学习，也即AC原来返回给Client成功的数据消失了。

不知我理解的是否正确，请帮助解释，感谢！

**Comment by pecywang** [comment]
仔细看了下B3约束，我提的场景AC对一个新value在InstanceId=2上达成决议应该是不存在的，A的acceptor会保留当时选择的值，那么在B离群的情况下，无论是A还是C做Proposer，原来A accept的value都不会改变，新Proposer也会感知到当时的value，所以ABC对已达成多数派的数据是一致的。

不知道我现在理解的是否正确，盼复，谢谢！

**Comment by unixliang** [comment]
你理解得很对，既然 instanceid 2 已经 chosen 了，那它的value就不会再变。
