### ISSUE TITLE
phxpaxos的自杀机制是什么时候触发

### ISSUE THREAD

**Issue by bh841128** [Tencent/phxpaxos#102]
phxpaxos的自杀机制是什么时候触发，为什么需要自杀

**Comment by unixliang** [comment]
当自己的chksum与其他节点的chksum不一致时会自杀，避免不一致扩散。
可以看看代码里在什么位置调用了```Instance :: ChecksumLogic```

**Comment by bh841128** [comment]
嗯，这个代码我看到了，我想问的是，什么情况下会导致触发该逻辑

**Comment by unixliang** [comment]
程序有bug，出现拜占庭错误等情况，例如硬盘数据变了。
