### ISSUE TITLE
CheckpointSender :: SendCheckpoint发送两遍的问题

### ISSUE THREAD

**Issue by max-feng** [Tencent/phxpaxos#106]
这个函数里发送两次SendCheckpointBegin，看了之前关于这个问题的恢复：tcp重连时第一个数据包会发送失败，这里重试了2次。

如果两次都成功了就会调用两次CheckpointReceiver :: NewReceiver，把.bak文件删除，备份的文件就被删掉了

这样，如果恢复checkpoint的时候目标度啊宕机是否会丢失数据

**Comment by unixliang** [comment]
备份文件被删并不会影响数据可靠性。只要多数派数据可靠，即使作为少数派的learner数据被清空，从外部看来也没有丢数据。
