### ISSUE TITLE
源码中prepare阶段 条件为 >=的疑问

### ISSUE THREAD

**Issue by Auraliano** [Tencent/phxpaxos#107]
关于 Acceptor.cpp  206行
 
int Acceptor :: OnPrepare(const PaxosMsg & oPaxosMsg)
{
    ....
    .
    .
    if (oBallot >= m_oAcceptorState.GetPromiseBallot())  这里为何可以有等于的情况？
   
    在等于情况下，是如何规避不会违反 paxos第一条规则（先后提出两个相同的Bal,对应不同的value的票）？

**Comment by kangzhanlei** [comment]
只要是小于已经 promise 的 proposalID的直接拒绝应该没有异议.  等于的时候, 也会把当前已经承诺过的proposalID对应的 value 回复给请求方, 请求方拿到结果之后, 发现同一个proposalID对应两个不同的 value, 一个是自己提出的 value, 另外一个是接收到别人的 value, 那么就需要一个策略, 来决定到底取谁的 value, 这个策略不需要很复杂, 只要能根据规则确定一个就好了, 是谁都无所谓. 在源码里, 他的规则是取NodeID最大的这个节点发出的 value 值.  (nodeid 就是根据 ip 和 port 进行位移算出来的一个long 型数据) , 然后proposer 会带着最终确定的 value 值, 进行 accept 请求.

**Comment by firnsan** [comment]
@kangzhanlei 你说的应该不是很对吧. 因为`if (oBallot >= m_oAcceptorState.GetPromiseBallot())`中的比较是用BallotNumber进行比较的, 也即是用上了nodeID和proposeID. 这里的==条件应该是只有prepare超时重试的时候成立, 因为proposeID和nodeID还是一样. 对于这种prepare超时的情况, proposeID不递增也可以继续工作. 没有==这个条件的话估计proposeID就要递增了.

**Comment by kangzhanlei** [comment]
嗯,我理解错误了, [issue34](https://github.com/Tencent/phxpaxos/issues/34)有关于这个的说明.

**Comment by firnsan** [comment]
Thanks, 也学习下
