### ISSUE TITLE
单 group 里可以使用并发处理吗? 

### ISSUE THREAD

**Issue by kangzhanlei** [Tencent/phxpaxos#108]
我想关于phxpaxos 里单 group 中, 并发的问题请教一下, 目前看来只有 instance0 完成的时候, 才会进行 instance1的操作. 所以在单个 group 里完全就是一个串行的操作, 这里有没有可能修改为并行操作来提升效率? 

例如下图: 
<img width="692" alt="2018-01-29 4 11 29" src="https://user-images.githubusercontent.com/1404345/35499859-20efdf8a-050f-11e8-95c4-18c9d95d9405.png">

假设客户端并不是一个一个 instance 的发送,而是携带者instance 编号1-8 批量对 phxpaxos 进行请求,   请求进入到了 phxpaxos 的节点之后,(假设节点分别为 A,B,C)  

A,B,C 三个节点, 每个节点分别启动3个线程(例如图中三个不同的颜色), 每个线程处理一个instance 的值的确定. 

然后我们设定一个环, 环有数量限制, 比如1-30号, 等1号 instance 的值最终确定下来之后, 写入1号环里. 2号 instance 的值确定之后写入到2号环里.因为每个 instance 都是互不影响的啊, 你确定你的,我确定我的,这样可以做到并发确定 instance 的值.

当环里某项的值确定之后, 再通知状态机去变更, 但是前提是他的前序节点已经变更结束. 也就是说2号虽然已经确定了值,但是并不会提交到状态机,而是等1号的值确定成功并且发布到状态机之后,  才会执行 . 这样能保证状态机里始终都是按照顺序提交的.

**Comment by xieyilun** [comment]
我理解性能问题靠BatchPropose就可以解决，如果像你这样并发处理，成员变更操作就会变得很麻烦，得参考raft那么搞了

**Comment by kangzhanlei** [comment]
batch 应该指的是一个 instance 里, 对应多个状态机的操作.  把多个操作合并到一个 instance 里,可以便面多次发起 instance 带来的效率问题.  但是 instance 还是串行的, 假设一个 instance 处理时间是10ms, 那么这个 instance 的 TPS 也可能就是1000/10 =100了, 即使有多个Group, 也只是充分利用了 cpu, 并没有给当前的 instance 带来什么效率上的提升. 如果一个系统的请求需要依赖多个 Group, 那么耗时最久的 Group 就是这个系统的瓶颈. 对吧.

**Comment by bh841128** [comment]
我理解性能问题靠BatchPropose就可以解决，如果像你这样并发处理，成员变更操作就会变得很麻烦，得参考raft那么搞了
=====
似乎raft才是完全得串行？我没看过相关开源实现，不过开论文他不是要求日志完全连续吗？虽然工程上也可以优化。。。

**Comment by bh841128** [comment]
楼主这样设计似乎可行，不过达成协议的时候，可能前面Instanceid还没达成协议，这个时候是否写paxoslog?如果不写，挂了以后似乎就完全木有记忆了，如果写了的话，paxoslog就会有空洞了，这个时候处理起来会复杂很多?

**Comment by kangzhanlei** [comment]
每个 instance都写自己的 paxoslog, 每个 instance 都是一个单独的 paxos 流程, 互不影响, 他们的顺序由 ringBuffer 决定, 不知道您说的空洞的意思是?

**Comment by lynncui00** [comment]
这个做法是可行的，具体在paxos made simple最后又稍微提到。

对于性能提升有帮助，特别在节点之间延迟很大的情况下，提升会比较大。在超低延迟的同城机房部署情况下，提升就相对一般。

代码逻辑也会变得相对复杂很多，特别是成员变更，需要一个填补空洞的操作（论文有提到）
