### ISSUE TITLE
PhxPaxos 中如何才能更严格的使用 Master 功能?

### ISSUE THREAD

**Issue by hidva** [Tencent/phxpaxos#112]
PhxPaxos 中如何才能更严格的使用 Master 功能?

PhxPaxos 在[PhxPaxos使用经验以及可能遇到的问题](https://github.com/Tencent/phxpaxos/wiki/PhxPaxos%E4%BD%BF%E7%94%A8%E7%BB%8F%E9%AA%8C%E4%BB%A5%E5%8F%8A%E5%8F%AF%E8%83%BD%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98)这篇 wiki 中提到使用 master 功能的正确姿势. 按照此姿势实现一个多副本 kv 存储. 其中仅配置了一个 group, group.bIsUseMaster 为 true, 仅由 master 节点来负责处理客户端读写请求; 同时也往 group.vecSMList 中增加一个 KVSM 对象, 负责处理客户端读写请求. 其中 KVSM::Execute() 实现伪代码如下:

```c++
bool KVSM::Execute(const int grpid, const uint64_t insid, const std::string &val,
  SMCtx *ctx)
{
  auto req = From(val);

  uint64_t master_ver;
  auto *node = GetNode();  // # 1
  node->GetMasterWithVersion(grpid, master_ver);

  if (master_ver != req.master_ver) { // # 2
    // 此时表明 master 发生过变更.
    if (ctx != nullptr) {
      ctx->kvctx.ret = kNeedRetry;
    }
    return true;
  }

  return DoExecute(grpid, insid, req, ctx);
}
```

同时 KVSM 未实现 checkpoint, 其 GetCheckpointInstanceID() 总是返回 NoCheckpoint, 即 -1. 根据 phxpaxos 源码来看, 负责 master 选举的 MasterStateMachine 实现了 checkpoint, 而且是在每次 Execute() 之后生成 checkpoint.

1.  在节点 A, B, C 上部署该多副本 kv 存储服务; 节点 A 在 paxos instance 0 中提议自己为 master, 被 A, B, C 一致批准并被选择. 此时 master 为 MasterInfo(node=A, ver=0).

2.  节点 A 收到 client1 Put(keyA, valA) 请求, A 在 paxos instance 1 中提议 `Request(op=kPut, key=keyA, val=valA, master_ver=0)`, 被 A, B, C 批准选择并交于 KVSM 执行. client 得到响应: Put(keyA, valA) 成功执行.

3.  节点 A 收到 client1 Put(keyB, valB) 请求, A 调用 GetMasterWithVersion() 返回 MasterInfo(node=A, ver=0), A 开始执行 `Propose(Request(op=kPut, key=keyB, val=valB, master_ver=0))`. 但是在 A 调用 GetMasterWithVersion() 返回之后, 在 Propose() 之前, A master 租约到期而且由于某些原因 A 未能成功续约, 导致 master 被节点 C 在 paxos instance 2 中抢去并得到 A, B, C 批准选择. 此时 master 为 MasterInfo(node=C, ver=2). A 发起的 Propose 在 paxos instance 3 中执行并被 A, B, C 批准选择交付于 KVSM. 在 KVSM::Execute() 中 `master_ver` 为 2, `req.master_ver` 为 0, 所以 Put(keyB, valB) 并未实际写入. client 得到响应 kNeedRetry.

4.  节点 C 收到 client2 Put(keyC, valC) 请求, C 在 paxos instance 4 中提议 `Request(op=kPut, key=keyC, val=valC, master_ver=2)`, 被 A, B, C 批准选择并交于 KVSM 执行. client 得到响应: Put(keyC, valC) 成功执行.

5.  节点 A 上的存储服务 core dump 并被立刻拉起. 根据 SMFac::GetCheckpointInstanceID() 逻辑此时会从 paxos instance 0 开始 PlayLog. 不过在此之前会执行 MasterStateMachine::Init() 来从 MasterStateMachine 的 checkpoint 中恢复 MasterStateMachine 状态. 即在从 paxos instance 0 开始 PlayLog 之前, master 信息为: MasterInfo(node=C, ver=2).

6.  节点 A 重放 paxos instance 0 的提议值, 根据 MasterStateMachine::Execute() 逻辑此时会直接 return true.

7.  节点 A 重放 paxos instance 1 的提议值 `Request(op=kPut, key=keyA, val=valA, master_ver=0)`, 在 KVSM::Execute() 中, 此时 `master_ver` 为 2, `req.master_ver` 为 0, 所以 Put(keyA, valA) 并未实际写入!!!

8.  节点 A 重放 paxos instance 2 的提议值, 与步骤 6 一样.

9.  节点 A 重放 paxos instance 3 的提议值, 与步骤 7 一样.

10. 节点 A 重放 paxos instance 4 的提议值, Put(keyC, valC) 被成功写入.

所以现在有几个问题:

- **Q**: 由于在 StateMachine::Execute() 中引入了 GetMasterWithVersion() 导致 StateMachine::Execute() 的行为在线上环境执行与在 PlayLog 环境执行不一致导致了未定义的结果, 该如何处理这种情况? 这里'线上环境'是指步骤 1, 2, 3, 4; 'PlayLog 环境' 是指步骤 6, 7, 8, 9, 10.

- **Q**: 由于在 StateMachine::Execute() 中引入了 GetMasterWithVersion(), 所以需要在 StateMachine::Execute() 中获取当前 Node 对象地址, 即 GetNode(). 因为当前 Node 对象地址需要在 Node::RunNode() 返回之后才可知, 所以 GetNode() 可能的实现如下:

  ```c++
  class KVSM: public StateMachine {
  public:
    // ... 略 ...
    Node* GetNode() const {
      return node_;
    }

    void SetNode(Node *node) {
      node_ = node;
      return ;
    }
  private:
    Node *node_ = nullptr;
  };

  int main(int argc, char **argv) {
    // ... 略 ...
    Node *node = nullptr;
    Node::RunNode(option, node);
    kvsm.SetNode(node);
    // ... 略 ...
  }
  ```

  但是此时在 RunNode() 返回之后, SetNode() 之前存在时间窗口, 可能会出现线上环境下 KVSM::Execute() 中 GetNode() 返回 nullptr. 不过此时 KVSM::Execute() 可以如下实现来解决:

  ```c++
  bool KVSM::Execute(const int grpid, const uint64_t insid, const std::string &val,
    SMCtx *ctx)
  {
    // ... 略 ...
    auto *node = GetNode();  // # 1
    if (node == nullptr) {
      // 让 phxpaxos 再一次调用 Execute()
      return false;
    }
    // ... 略 ...
  }
  ```

  最关键的是在 PlayLog 环境下的 KVSM::Execute(), 由于 SetNode() 逻辑尚未执行, 其中 Execute() 内部的 GetNode() 总是返回 nullptr, 导致无法获取 master 相关信息, 又该如何处理?

**Comment by lynncui00** [comment]
WIKI里面描述的不好，本意是介绍了一种实现方法，但描述时候结合了phxpaxos目前提供的函数，但事实是做不到的，因为目前master是独立构建checkpoint，这种情况下master版本号会出现跳跃，导致您问题描述的情况，跳跃不止发生于重启的时候，也可能发生于落后太多，从别的机器直接同步checkpoint的时候。

要实现严格的master，用户sm的checkpoint必须要和master的checkpoint结合起来一体化构建，比如在phxsql里面就是这么做的。但是这要求用户自己实现master功能，管理master数据，构建master checkpoint，对于一般使用者来说太复杂了。所以目前的版本master功能是独立的。

要实现严格的master还有另外一种方法，就是通过sm的BeforePropose功能，来检测当前最新的master，如果master不是自己，则可以修改value来达到拒绝的效果。这种方法不需要在execute函数检测master。

**Comment by hidva** [comment]
那是不是可以按照 [https://blog.hidva.com/2018/02/27/PhxPaxos-Group-MultiSM/](https://blog.hidva.com/2018/02/27/PhxPaxos-Group-MultiSM/) 这里的思路调整 PhxPaxos 多状态机的实现方式:

>   这里介绍了实现多状态机的另一种思路, 即通过"栈"的方式实现多状态机, 将多个状态机组织成状态机栈. 这时 checkpoint 的构建由栈底状态机驱动, 栈底状态机在时机合适构建好 checkpoint 之后, 会将该 checkpoint 向栈顶方向传递, 每一层 StateMachine 构建完自身的 checkpoint 之后将其追加到下层生成的 checkpoint 之前然后向栈顶方向传递, 栈顶状态机会负责持久化最终的 checkpoint. 在从 checkpoint 中恢复时, 则将 checkpoint 从栈顶到栈底方向传递, 每层 StateMachine 提取出自己的 checkpoint 信息并利用该信息恢复自身的状态. 这里根据状态机之间的依赖关系来组织状态机栈, 若 StateMachine A 依赖于 StateMachine B 的状态, 那么 B 应该在 A 之上.
>   
>   这时一些负责处理常见功能的状态机, 比如负责 master 选举的状态机, 负责实现 membership 变更都的状态机可以事先实现; 用户只需要实现负责处理自身业务逻辑的状态机; 然后根据状态机之间的依赖情况来组织状态机栈.

这样一方面可以统一一体化地构建 checkpoint; 另外一方面也不需要用户开发额外的逻辑.

**Comment by lynncui00** [comment]
checkpoint涉及到的细节太多，除了重启恢复，还包括如何构建，构建的时机，跨机传输等等。实际实现出来的效果如何，用户开发的难度如何也无法简单分析。所以没办法回答是不是，这个需要很细致的进行全盘分析，要照顾的各个分支细节。

**Comment by hidva** [comment]
好咧

**Comment by huangyu6572** [comment]
测试过程 中， BeforePropose 似乎也不准确，
在beforePropose 时A为master
然后网络断开，
导致A  propose 返回 超时
然后网络恢复,
A 自动重试执行了execute,导致写的一致性被破坏
