### ISSUE TITLE
为什么剩余时间小于200ms就不提交了呢？

### ISSUE THREAD

**Issue by liuliuwd** [Tencent/phxpaxos#115]
int Committer :: NewValueGetIDNoRetry(const std::string & sValue, uint64_t & llInstanceID, SMCtx * poSMCtx) {
......
    int iLeftTimeoutMs = -1;
    if (m_iTimeoutMs > 0)
    {
        iLeftTimeoutMs = m_iTimeoutMs > iLockUseTimeMs ? m_iTimeoutMs - iLockUseTimeMs : 0;
        if (iLeftTimeoutMs < 200)
        {
            PLGErr("Get lock ok, but lockusetime %dms too long, lefttimeout %dms", iLockUseTimeMs, iLeftTimeoutMs);

            BP->GetCommiterBP()->NewValueGetLockTimeout();

            m_oWaitLock.UnLock();
            return PaxosTryCommitRet_Timeout;
        }
    }
......
}

**Comment by lynncui00** [comment]
这个是一个经验值，一般在等锁等了这么长时间的情况下，系统肯定处于不稳定状态，剩余200ms可能很大概率还是超时失败，干脆就放弃这个请求。

**Comment by liuliuwd** [comment]
明白了 多谢。
