### ISSUE TITLE
paxosstore和phxpaxos

### ISSUE THREAD

**Issue by cxucheng** [Tencent/phxpaxos#132]
我想问问两个项目的区别，根据文档，这里两个项目都声称在wechat里用过，请问有没有性能比较呢？所以wechat里面是两个系统同时在用吗？

**Comment by unixliang** [comment]
> 我想问问两个项目的区别，根据文档，这里两个项目都声称在wechat里用过，请问有没有性能比较呢？

没有性能比较。

> 所以wechat里面是两个系统同时在用吗？

是的，规模都不小。
