### ISSUE TITLE
是否通过了Jepsen测试？

### ISSUE THREAD

**Issue by Tachone** [Tencent/phxpaxos#134]
Jepsen是开源社区比较认可的一致性测试框架， 像braft、X-Paxos等都通过了Jepsen测试，  不知道phxpaxos有没有做这方面的工作， 是否通过Jepsen测试， 或者有没有这样的计划？

**Comment by unixliang** [comment]
有计划支持。
phxpaxos也有类似jepsen的错误注入测试，但即使测试通过了也不能说明没有一致性问题，所以phxpaxos通过实时校验plog chksum的方式来发现不一致，并通过自杀来阻止不一致扩散。目前在生产环境中暂没出现不一致案例。
