### ISSUE TITLE
为什么只支持linux64平台呢，不支持window平台呢

### ISSUE THREAD

**Issue by PangooWang** [Tencent/phxpaxos#39]
什么时候支持windows平台

**Comment by lemon0910** [comment]
现在互联网后台一般都用linux吧，写可移植的代码太麻烦了吧。。

**Comment by lynncui00** [comment]
@PangooWang 暂时没有支持windows平台的计划。

**Comment by boolking** [comment]
我简单的[移植](https://github.com/boolking/phxpaxos/tree/win_port)了一下，已经可以支持windows了。
Unit test和echo，election都可以正常运行。

针对windows做了如下修改：
1. 使用gyp简化编译流程，不需要单独编译第三方库。linux下使用[gyp+ninja替代make](https://github.com/boolking/phxpaxos/blob/win_port/gyp_build.sh)，windows[使用vc2017](https://github.com/boolking/phxpaxos/blob/win_port/gyp_build.bat)；
2. 在windows使用select简单模拟了一下poll/epoll的行为，并修改了SocketBase相关的一些实现来支持windows；使用Windows API模拟fsync/fdatasync/truncate；使用rmdir()替代remove()来删除空目录；
3. 使用std::thread替代pthread，移除了一些没有使用的线程函数和ThreadAttr类；
4. **由于[std::unique_lock跨线程使用不安全](https://stackoverflow.com/questions/18937564/unique-lock-across-threads)，使用std::condition_variable_any替代std::condition_variable，还能够减少一次函数调用；**
5. 使用__VA_ARGS__替代args...；
6. 添加了leveldb的windows支持，更新gtest/gmock到1.8.0，修正了glog在vc2017下的一些编译错误；
7. 修改[travis.ci](https://travis-ci.org/boolking/phxpaxos)的配置文件，添加了[appveyor](https://ci.appveyor.com/project/boolking/phxpaxos)的配置。windows和linux都可以正常编译。

**Comment by lynncui00** [comment]
@boolking 非常感谢，这是一个非常大的pull requests，我们需要相当的时间来进行review. 但在这之前，希望你能先排除掉由于空格，换行符等带来的代码变动，降低diff复杂度。

**Comment by PangooWang** [comment]
非常感谢！做的很好，希望以后有更多的人参与windows下的维护，使其适用于更多的平台

**Comment by PangooWang** [comment]
问一下是VC2017还是VS2017，关于编译有详细的文档吗，另外windows版本是否离应用于生产环境还很很远

**Comment by boolking** [comment]
@lynncui00 这个移植只是为了快速支持windows，选择的都是我较熟悉（gyp，vc）和对原有代码改动最小的方式（模拟linux的头文件和函数）。
如果官方版本有意支持windows，可能有些部分需要先讨论一下：
1. 选择一个合适的跨平台编译及工程管理方式，便于从一开始就加入CI支持。gyp官方已停止支持，bazel/gn/cmake/premake等都是可行的选择；
2. 建议在支持windows之前先进行一些简单的清理，如去除行尾空格，tab改为space，去掉未使用的函数，使用标准库，修正打印格式化等，这个我会先提一些单独的pull request；
3. 对git submodule的修改，为了尽量少进行改动，我采用的是在编译脚本中copy覆盖原文件的方式（leveldb和glog）。最好的方式当然是自己fork这些third_party library进行修改，这些fork存放在哪里？
4. windows需要支持的编译器版本，目前vc2017已经可以支持了，我手边还有一个支持vc2010的版本（使用boost来兼容c++11的部分标准库，并用脚本替换了range-based for loop）；
5. 直接修改代码与模拟linux的函数及头文件的权衡。模拟的方式对原有代码侵入性最小，但是某些文件（stdio.h和stdlib.h）无法模拟。

**Comment by boolking** [comment]
@PangooWang 理论上来说只需要msbuild+vc2017即可编译了，运行gyp_build.bat生成.sln/.vcxproj，msbuild进行编译，当然也可以使用VS2017 IDE打开进行编译修改。
是否能用于生产环境，我还没有深入测试过，只是把unittest和sample跑了一下，基本没有什么问题，如果存在windows port相关的bug也会继续fix，欢迎提出issue。

**Comment by lynncui00** [comment]
@boolking 我先前的回复是针对那个大pull requests做的简单回应。我们官方目前暂时不会在windows版本做出努力，毕竟服务器端还是linux为主。但如果我们获得的pull requests质量很高，并且不影响到现有linux用户的使用质量，我们也是考虑合入代码的，当然这个代码编写可能很复杂，繁琐，而且也要经过我们相当长时间的代码review。

**Comment by boolking** [comment]
@lynncui00 没问题，我已经将部分针对linux部分的修改提出了新的的pull request。
后续我还是会维护独立的fork，并提出合适的pull requests。
