### ISSUE TITLE
请问 每个paxos group 目录下的 vfile这个目录是用来做什么的？

### ISSUE THREAD

**Issue by haiyaguixin** [Tencent/phxpaxos#45]
如： 
root@localhost vfile]# pwd
/root/phx-test/logpath_172.17.111.54_9527/g0/vfile
[root@localhost vfile]# ll
total 12
-rw-------. 1 root root 104857600 Mar  1 02:25 0.f
-rw-------. 1 root root       158 Feb 28 22:05 LOG
-rw-------. 1 root root         0 Feb 28 02:18 meta
[root@localhost vfile]# 

这些文件的作用是什么

能否再给出一些实现原理介绍文档，这个项目感觉原理介绍的文档比较少，除了工程实现那篇文章

**Comment by lynncui00** [comment]
您好，vfile是paxos log的实际内容，而leveldb存储的只是索引。为何要索引和内容分离呢？其中有几个原因。
1. 索引我们是采用异步写盘，只有vfile才使用fdatasync来同步写盘。那么损耗的只是多了一次系统调用和内存写入而已，我们的瓶颈在于磁盘同步写盘的次数，所以这个损耗不大。
2. 如果只采用lsm结构的leveldb进行paxos log的存储，那么会带来很大数据量的compact开销。
3. 考虑到我们的Paxos log是基于InstanceID的写入顺序来进行数据删除的，那么进行索引内容分离后，vfile作为内容数据，很方便的就可以进行整个文件的删除，这样就避免了leveldb大数据compact的损耗，最大的发挥了leveldb的性能。
