### ISSUE TITLE
LogStorage的路径一定要是绝对路径吗

### ISSUE THREAD

**Issue by niukuo** [Tencent/phxpaxos#49]
在接收checkpoint的时候遇到错误，发现原因是 CheckpointReceiver::InitFilePath 中会无条件在路径前加"/"，原本的相对路径变成了绝对路径，没有权限mkdir失败。

**Comment by lynncui00** [comment]
可能不支持，我们对相对路径没有做过专门的测试。

**Comment by lynncui00** [comment]
您好，最新的代码解决了这个问题。
