### ISSUE TITLE
请问proposer提交一个新值时可以忽略prepare流程直接accept的原因

### ISSUE THREAD

**Issue by lichuang** [Tencent/phxpaxos#52]
在函数Proposer :: NewValue中，当满足m_bCanSkipPrepare && !m_bWasRejectBySomeone这两个条件的情况下，可以直接跳过prepare阶段直接到accept，从代码中看到，m_bCanSkipPrepare只要在这一轮prepare有半数通过就会置为true，m_bWasRejectBySomeone就更简单明了，就是这一轮提交中没有被其他参与者拒绝过。

我想问下，这个优化的理论依据是什么？有什么资料可以给来看看吗？

**Comment by chenneal** [comment]
multi-paxos在没有冲突的情况下可以省略prepare阶段，具体看作者写的文章：
[Paxos理论介绍(2): Multi-Paxos与Leader](https://zhuanlan.zhihu.com/p/21466932)
还是推荐先把理论搞懂再去看代码。
