### ISSUE TITLE
phxpaxos 内存（RES）一直在涨

### ISSUE THREAD

**Issue by wilesduan** [Tencent/phxpaxos#61]
把phxpaxos 嵌入到我们的框架中，空跑，不做rpc任何调用，观察了内存使用率一致在涨。用valgrind看，没有内存泄漏。一共有30个paxos group, 发现主group较多的node内存涨的快。不知道为啥。

**Comment by lynncui00** [comment]
占用一定量的内存是正常的，但是一直往上涨的情况我们在测试和生产环境都没遇到过。可以尝试观察一下内存的增长能否在一个值稳定下来。
