### ISSUE TITLE
Database::PutToLevelDB耗时3s多，这种问题怎么解决

### ISSUE THREAD

**Issue by wilesduan** [Tencent/phxpaxos#63]
测试的时候遇到偶尔超时严重，通过打点记日志发现Database:: PutToLevelDB偶尔耗时3s多，我想问问你们在实际场景中怎么解决这个问题？修改leveldb代码？

**Comment by lynncui00** [comment]
leveldb写入很慢原因是因为遇到compact数据，但是phxpaxos的设计leveldb只负责存储索引，所以compact是非常的轻量，compact耗时较长属于极少之情况。目前在我们生产环境上监控PutToLevelDB耗时超过500毫秒的不到百万分之一，所以是可以接受的。如果你这种高耗时情况经常发生，可能需要检查一下是否磁盘过载的原因。
