### ISSUE TITLE
propose冲突的问题

### ISSUE THREAD

**Issue by xinmingyao** [Tencent/phxpaxos#64]
3台master，偶尔会出现propose的错误：
PN8phxpaxos18MasterStateMachineE::LearnMaster version conflit, op version 14793487 now master version 14793495

目前3台master是每台机器都能propose的，是否需要将所有propose业务都rpc到master去做propose？

**Comment by chenneal** [comment]
我的想法是你可能误会了「master」和「leader」的定义了。你说的三台「master」其实是指的「leader」，我简单的定义一下二者的概念：

+ leader节点是指有权限propose的节点，不唯一。
+ master节点是指唯一有权限propose的节点且任意时刻不会出现超过一个master节点的情况。

既然你使用了phxpaxos内置的选主算法，就不应该再在三个节点上去进行propose了，而是应该在应用层重定向每一个访问到唯一的master节点中去。

希望答案对你有帮助，这个解释是否正确还是要看作者的回复。

**Comment by xinmingyao** [comment]
不好意思，我上面描述的不是很清楚，有3个节点，现在是每个节点都做propose，偶尔会propose冲突，是否需要将所有propose通过应用层的RPC到master上去做propose

**Comment by chenneal** [comment]
@xinmingyao 好吧，讲通俗一些，既然你用了master这个功能，就不能复数propose，也就是说需要重定向RPC到master节点。

另外不太明白你这个错误日志是啥，你自己写的test？

**Comment by lynncui00** [comment]
@xinmingyao 
1. 你贴的这个日志不是propose冲突的日志，而是Master SM execute一些过期的Paxos Log，是正常现象来的。
2. 在三个节点同时Propose确实是会出现冲突的，这种情况Propose会返回PaxosTryCommitRet_Conflict，详见def.h。遇到冲突，一般只需要重试几次就能成功，但不建议在大量请求规模下这样使用。
3. 冲突并不会产生一致性问题，但是会影响效率，所以建议大部分请求还是单点Propose.
4. Master的出现，第一是为了解决效率问题，第二是为了解决读的一致性问题，也就是如果写入都在Master上完成，那么必定都能在Master上读出来，这样读的时候就无需跨机访问多数派，效率就会变得非常高。

@chenneal 
1. 开启Master后，并不强制要求在Master上写，比如一些请求量比较少（少量的冲突不会影响整体性能），又必须在其他节点写入的请求，仍然是可以直接进行Propose的，只不过这些请求的读一致性就难以保证。这个具体怎么使用完全看业务，非常灵活。这也是Master比Leader好的地方。

**Comment by chenneal** [comment]
@lynncui00 感谢回复，看完了您的回复，还是觉得这么设计会给 phxpaxos 库的使用者带来不少的理解难度的。大概的阐述一下我的理解：

想要满足「强一致读」，那么所有的读写请求必须都在master节点上进行。

如果要分散少量的写到别的节点进行propose，可以操作，但是这些少量的propose的数据将无法满足强一致读。

就是说phxpaxos只提供了 master 与 leader 的实现，如何去访问完全交给了上层应用，虽然变灵活了，但是对开发者要求有些高。

**Comment by lynncui00** [comment]
@chenneal 如果希望把paxos应用到大规模生产环境，其实本身对开发者的要求就很高，访问规则这个只是开发者要考虑的问题里面很小的一个问题。而如果希望学习paxos或者做一些学术实验，那么就更应该多深入理解了:)
