### ISSUE TITLE
是否支持双机房部署A和B，当断开是否是否存在脑裂，是否支持双机房主从灾备

### ISSUE THREAD

**Issue by alexliu5678** [Tencent/phxpaxos#67]
1：是否支持双机房A和B主备部署
2：如果支持双机房，当两个机房断开是否存在脑裂两个机房都存在master

**Comment by lynncui00** [comment]
您好
1. 一般Paxos算法建议3台或以上机器部署，可部署在多个机房。（推荐部署在3个机房，每个机房一个节点）
2. Paxos算法不存在脑裂问题。
3. Paxos不是主从模式，至少需要3个节点才能进行容灾。
