### ISSUE TITLE
在slave同步过程中取master的问题

### ISSUE THREAD

**Issue by xinmingyao** [Tencent/phxpaxos#68]
在slave同步过程中如果调用 GetMaster获取的NodeInfo信息会不断的变化，有时候能取到正确的master的ip和port，有时候会取得到ip为空，port为0，而且会交替出现，有没接口判断这台slave已经同步好

**Comment by lynncui00** [comment]
1. slave同步过程和master持续写入是同时进行的，所以slave需要同步的instance也是不断在更新，很难判断当前机器是不是最新状态。而唯一能判断的方法就是进行一次propose，在propose成功的这一个瞬间，这台机器的数据肯定是最新的。

2. 由于数据无法时刻同步的原因，判断一个节点是否master，必须是自己认为自己是master，不能以其他节点的信息作为是否master的判断。比如A,B,C三个节点，C认为B是master，这时候还需要到B节点确认B是否是master，才能确定B是master。

3. 在slave同步过程中，GetMaster获取到的NodeInfo信息是一个过期的master信息，但决不会是自己本身，所以不会出现同时有两个master的错误。
