### ISSUE TITLE
master_sm中将新Master合入本地状态机时，两个Version的判断如何理解

### ISSUE THREAD

**Issue by cnkuangshi** [Tencent/phxpaxos#74]
if (oMasterOper.lastversion() != 0
            && llInstanceID > m_llMasterVersion
            && oMasterOper.lastversion() != m_llMasterVersion)

if (oMasterOper.version() != m_llMasterVersion)

**Comment by lynncui00** [comment]
`oMasterOper.version()`是本次Master的版本号，`oMasterOper.lastversion()`上一次版本号。

last version在这里不是必要的，这里是用来校验一致性。只有当各个节点的last version一致，才可以更新到本次最新的master version。 因为当各个节点master信息不一致的时候，就有出现同时多个master的风险。

一些最极端的情况可以使得master信息不一致，比如：
- master信息被人为篡改。
- 程序的bug导致各节点master信息不一致。
- 重启后master信息丢失。
- 等等。

**Comment by cnkuangshi** [comment]
可以理解m_llMasterVersion是当前已知Master Version即所在Instance，如果发现当前已知的m_llMasterVersion与待写入状态机的新Master信息中lastversion不符，说明中间出现了未同步成功或脑裂，这种情况直接修正version会有风险么；

此外判断 if (oMasterOper.version() != m_llMasterVersion) 就报错返回，新Master的版本不是本应该大于当前记录的版本么，比较困惑

**Comment by lynncui00** [comment]
不好意思，前面的回复有点错误，我编辑了。

version和last version其实描述的是两个问题，一个是基于版本号的CAS更新，一个是用来校验一致性，你把这两部分代码分开来看，先去掉last version相关代码，看懂了version后，再看完整代码，这样比较容易理解。

**Comment by cnkuangshi** [comment]
提交新值时候CheckNewValue时会去设置set_lastversion(MasterVersion)
需要重选举时获取iMasterNodeID, llMasterVersion，并拿这个MasterVersion发起propose
达成共识写入状态机时，若检查到MasterVersion已经落后，直接更新到最新版本；若校正后的最新版本，和要合入的选举时的MasterVersion不一致，说明可能当前投票已经是上一个Instance的作废投票。

异常情况下，TryBeMaster时的跨进程读取MasterVersion时可能读到老数据、或MasterStateMachine自身就没更新成功，这些情况下的投票都是无效的，只有在正常情况下重选举才会成功被写入状态机。

这样解释可能会清楚些。

**Comment by lynncui00** [comment]
流程归纳很对。

关于疑问这里解释一下：
1. version还有另外一个含义，就是表示在这个version情况下可以发起TryBeMaster操作，但是在last version的时候就不一定了，所以不能直接用last version代替version来比较。
2. 如果在设置last version阶段来进行检查是否可以发起TryBeMaster也是可以的，但不这么做的原因是，我们尽量把与paxos无关的逻辑放在paxos主线程之外，在代码层面更清晰。

**Comment by cnkuangshi** [comment]
目前应用一致性协议中存在什么值得进一步探索的方向么，如果方便可通过kuangshi@kuangshi.info单独指教，谢谢
