### ISSUE TITLE
请问这是否是一个潜在的同步 bug？

### ISSUE THREAD

**Issue by Goclis** [Tencent/phxpaxos#75]
文件：src/communicate/tcp/tcp_client.cpp

在 AddMessage->GetEvent->CreateEvent 这条调用路径下，访问 m\_vecEvent 的时候使用了 mutex 进行同步，而 DealWithWrite 中访问 m\_vecEvent 时没有同步。

我个人理解前面这条路径是 TcpClient 的用户线程使用的，而后者是 TcpWrite 线程运行 EventLoop 的时候去调用的，所以应该是需要进行同步操作的。

类似地情况还发生在 MessageEvent::OnWrite 中对于 m\_oInQueue 的访问。

请问这是一个惯用的优化技巧么？或者是我对线程模型的理解不太正确？谢谢！

**Comment by lynncui00** [comment]
>在 AddMessage->GetEvent->CreateEvent 这条调用路径下，访问 m_vecEvent 的时候使用了 mutex 进行同步，而 DealWithWrite 中访问 m_vecEvent 时没有同步。

这个`m_vecEvent`的`size`是只增不减的，参考`DealWithWrite`的实现应该没有安全隐患。

>类似地情况还发生在 MessageEvent::OnWrite 中对于 m_oInQueue 的访问。

这里对`m_oInQueue.empty()`的使用确实有隐患，好在后面的`DoOnWrite`重新加锁做了二次校验，所以这个问题被规避掉了。

这部分代码写得不够优雅，有机会调整一下，谢谢指出:)

**Comment by Goclis** [comment]
虽然 m\_vecEvent 是只增不减的，但是代码中没有对 m\_vecEvent 进行一些 reserve 的操作，所以个人感觉 CreateEvent 中的 `m_vecEvent.push_back(poEvent)` 依旧可能会引起一些扩容操作。这是否也会对 DealWithWrite 中的访问带来一些安全隐患呢？

以 VS2013 上的非 const 版本的 vector::operator[] 实现为例，内部有个 `return (*(this->_Myfirst + _Pos))` 语句，而扩容过程是会导致 \_Myfirst 指针变化的，从而未同步情况下这个语句有可能会访问了一块已被释放的内存。

不过如果一开始 reserve 一块大小够用的空间的话，确实可以避免安全隐患，不知道我的理解是否正确？

**Comment by lynncui00** [comment]
你说的很对，这里确实有疏漏。

**Comment by Goclis** [comment]
非常感谢你的解答~

**Comment by lynncui00** [comment]
刚好今天准备更新代码，参照你的建议，对m_vecEvent做了一次reserve(1000)暂时规避风险，但如果连接超过1000个仍然有可能会出现问题，不过这个概率应该很低了。

后面有机会再调整代码解决这个问题和m_oInQueue的优雅性问题。
