### ISSUE TITLE
新master数据同步的问题

### ISSUE THREAD

**Issue by cugwoods** [Tencent/phxpaxos#76]
当master的某个提议通过以后并返回客户端， 但还未来的急通知其它节点时， master挂了， 由剩余节点选出一个master, 此时是怎么做到数据同步的呢， 仔细看了下代码，没有发现对这种情况的处理， 新的master是否需要重新对最新一次的数据执行一次paxpos呢,， 谢谢

**Comment by lynncui00** [comment]
`TryBeMaster`也是一次普通的`Propose`操作，这个操作会完成数据同步。

**Comment by cugwoods** [comment]
可能没有描述清楚， fg: 如果master已经通过instance 6 的proposer,  但是此时master 还没有成功发送MsgType_PaxosLearner_ProposerSendSuccess消息到其它节点， 那么集群中剩余节点是不知道instance 6提议已经通过， 集群中剩余节点的下次提议是否会覆盖instance 6的信息

**Comment by lynncui00** [comment]
instance 6的提议已经chosen的话，那么任意一个节点发起非chosen value的propose操作就会获得conflict的返回，然后再重试就是instance 7了。这是朴素算法的本质，已经chosen的value不会再被改变。

**Comment by cugwoods** [comment]
你的意思我懂， 但是虽然Instance 6的数值已经确定， 但是除了master节点知道外， 其它节点并不知道instance 6 的数值已经chosen， 但是此时master已经挂了，剩余节点发起propose操作的时候，虽然还是Instance 6 , 但也不会有节点conflict，因为没有节点知道上一次的propose操作已经chosen

**Comment by lynncui00** [comment]
你还没完全搞懂朴素paxos算法，建议看看wiki里面我写的第一篇理论文章，或者再细读一下论文。

**Comment by firnsan** [comment]
> TryBeMaster也是一次普通的Propose操作，这个操作会完成数据同步。
> instance 6的提议已经chosen的话，那么任意一个节点发起非chosen value的propose操作就会获得conflict的返回，然后再重试就是instance 7了。这是朴素算法的本质，已经chosen的value不会再被改变。

@lynncui00 你好.  对于这两句话, 我看代码理解是: proposer如果遇到Conflict会重试, 最多3次. 比如第一次是以instanceID=6进行提议, 第二次是7, 第三次是8, 然后停止重试了. 那么请问9,10,11...这些缺少的instance就不会补全了. 所以通过propose()只是补全3个instance, 其他的得依靠应用自己多调用几次propose()来补齐? 

> 遇到Conflict时, 特地对MASTER_V_SMID这个master选举的情况不进行重试又是基于什么考虑呢?
