### ISSUE TITLE
checkPoint可能多次回放的问题

### ISSUE THREAD

**Issue by cugwoods** [Tencent/phxpaxos#77]
1、再实例phxKv中， 当执行Execute的时候， 会执行SyncCheckpointInstanceID, 更新checkPointInstanceID, 这里每隔m_iSkipSyncCheckpointTimes才会存一次磁盘， 每次机器重启的时候， 会根据checkPointInstanceID来进行回放， 如果某次还未来得及存盘服务就挂了， 会导致某一实例的多次执行

2、int Instance :: ReceiveMsgForAcceptor(const PaxosMsg & oPaxosMsg, const bool bIsRetry)中当oPaxosMsg.instanceid() == m_oAcceptor.GetInstanceID() + 1)时直接将acceptor接受的value作为上一个实例的最终值， 这里可能会有问题， 上次一acceptor的接收的值， 不一定是上一个instance最终确定的数值，

**Comment by lynncui00** [comment]
1. PhxKV状态机支持幂等。在有超时的系统里面，同样的操作多次执行是不能避免的，需要状态机自身满足幂等性。
2. 需要看懂`OnProposerSendSuccess`就明白怎么回事了。
