### ISSUE TITLE
运行sample下的phxecho提示COULD NOT CREATE A LOGGINGFILE

### ISSUE THREAD

**Issue by songzhiqiangEx** [Tencent/phxpaxos#79]
Run cmd : ./phxecho 127.0.0.1:11111 127.0.0.1:11111,127.0.0.1:11112,127.0.0.1:11113

Then throws : COULD NOT CREATE A LOGGINGFILE 20171007-114442.4846!Could not create logging file: No such file or directory

I add the GLOG_log_dir environment variable solve this : export GLOG_log_dir=/home/hadoop/git/phxpaxos/sample/phxecho/logdf

May this should be noted in README file,or start script

**Comment by ya-ming** [comment]
My solution is to create 'log' folder at the phxecho folder.

**Comment by lynncui00** [comment]
My suggestion is same as @ya-ming's reply. I will make a hint for this on PhxEcho's README. Thanks.
