### ISSUE TITLE
GetNowInstanceID得到的不是全局最大的ID

### ISSUE THREAD

**Issue by xieyilun** [Tencent/phxpaxos#82]
文档中写的是：
“
const uint64_t GetNowInstanceID(const int iGroupIdx)

获取当前PhxPaxos正在进行的提议所对应的ID，也可认作全局最大的ID。
”
但是我在测试中，向集群中新加一个节点后，那个节点调用GetNowInstanceID得到的是本地正在提交的ID，不是全局的最大ID

**Comment by lynncui00** [comment]
已修正，谢谢。
