### ISSUE TITLE
C++11支持以及Future功能

### ISSUE THREAD

**Issue by wumuzi520** [Tencent/phxpaxos#86]
最近抽时间把整个代码看了一遍，有些地方不明白的看了好多遍，感觉里面的状态还是蛮复杂的，首先膜拜一下。

此外我想提个建议，有没有计划将支持c++11风格呢？
我看代码蛮多地方用到条件变量等待操作，如果将这些修改成future & promise形式看起来或需会更清晰一些哦，个人愚见！

**Comment by lynncui00** [comment]
挺好的建议。
