### ISSUE TITLE
checkpoint 中 ExecuteForCheckpoint是什么作用？触发周期是什么？

### ISSUE THREAD

**Issue by zhengcf** [Tencent/phxpaxos#87]
ExecuteForCheckpoint是什么作用？
触发周期是什么？
Replayer::run() 中
       llinstanceID>=m_poCheckpointMgr->GetMaxChosenInstanceID()
这个条件是什么意思？

**Comment by lynncui00** [comment]
还是与#51提到的一样，第一条TCP消息由于断线重连可能会丢失，所以先简单这么写了。

**Comment by lynncui00** [comment]
参考文章 [实现的一些原理和细节](http://mp.weixin.qq.com/s?__biz=MzI4NDMyNTU2Mw==&mid=2247483695&idx=1&sn=91ea422913fc62579e020e941d1d059e#rd) 中的Checkpoint章节， ExecuteForCheckpoint是利用双状态机的机制，协助开发者生成当前数据的镜像数据。

`llinstanceID>=m_poCheckpointMgr->GetMaxChosenInstanceID()`这个条件的意思是指生成的镜像截止到`m_poCheckpointMgr->GetMaxChosenInstanceID()`
