### ISSUE TITLE
调用learner发送两次checkpoint begin的原因是？

### ISSUE THREAD

**Issue by lichuang** [Tencent/phxpaxos#88]
void CheckpointSender :: SendCheckpoint()
{
    int ret = -1;
    for (int i = 0; i < 2; i++)
    {
        ret = m_poLearner->SendCheckpointBegin(
                m_iSendNodeID, m_llUUID, m_llSequence, 
                m_poSMFac->GetCheckpointInstanceID(m_poConfig->GetMyGroupIdx()));
        if (ret != 0)
        {
            PLGErr("SendCheckpointBegin fail, ret %d", ret);
            return;
        }
    }

**Comment by lynncui00** [comment]
还是与 #51 提到的一样，第一条TCP消息由于断线重连可能会丢失，所以先简单这么写了。
