### ISSUE TITLE
系统启动时，在哪里使用checkpoint中的数据进行恢复？

### ISSUE THREAD

**Issue by lichuang** [Tencent/phxpaxos#89]
checkpoint的作用是为了防止paxoslog无限增长，同时有了checkpoint，也不需要在启动时需要从第一条paxoslog开始进行重放来恢复整个系统的。

但是目前似乎没有看到在哪里使用checkpoint的数据进行恢复的，只看到了checkpoint文件的接收、发送、replay、clean。

**Comment by lynncui00** [comment]
checkpoint的恢复是由状态机自己完成的，也就是说在`Node::Run`之前，`options`设置好的`StateMachine`就需要把自身的checkpoint恢复好了，同时确保状态机的`GetCheckpointInstanceID`函数能获取到当前恢复的数据所代表的`InstanceID`

**Comment by duhuanming** [comment]
从checkpoint恢复数据后，怎么设置新数据的当前的instanceid。目前的情况是重新启动后，会再次收到checkpoint并再次覆盖。

**Comment by lynncui00** [comment]
@duhuanming `checkpoint`所对应的instanceid由状态机自己设置，并通过`GetCheckpointInstanceID`反馈出来。

另外checkpoint同步是很重的操作，需要保留一定量的paxoslog，避免经常同步checkpoint

**Comment by duhuanming** [comment]
问题已解决
