### ISSUE TITLE
为什么要使用旧的instance ID来学习新的值？

### ISSUE THREAD

**Issue by lichuang** [Tencent/phxpaxos#90]
int Instance :: ReceiveMsgForAcceptor(const PaxosMsg & oPaxosMsg, const bool bIsRetry)
{
 
    
    if (oPaxosMsg.instanceid() == m_oAcceptor.GetInstanceID() + 1)
    {
        //skip success message
        PaxosMsg oNewPaxosMsg = oPaxosMsg;
        oNewPaxosMsg.set_instanceid(m_oAcceptor.GetInstanceID());
        oNewPaxosMsg.set_msgtype(MsgType_PaxosLearner_ProposerSendSuccess);

        ReceiveMsgForLearner(oNewPaxosMsg);
    }
}

在上面的代码中，oPaxosMsg.instanceid() == m_oAcceptor.GetInstanceID() + 1表示这个值已经投票通过了，可以直接学习，但是为什么传入的instanceid要修改成m_oAcceptor.GetInstanceID() 而不是该消息的instanceid？

**Comment by lynncui00** [comment]
1. `oPaxosMsg.instanceid() == m_oAcceptor.GetInstanceID() + 1`并不代表当前acceptor所accept的值是chosen的值，也可能是未被通过的值，具体原因可以自己推敲一下。

2. 这里的目的是构造一条`ProposeSendSuccess`的消息。目的是用于判断这个accept value是否被chosen，并不是直接学习。

**Comment by bh841128** [comment]
oPaxosMsg.instanceid() == m_oAcceptor.GetInstanceID() + 1并不代表当前acceptor所accept的值是chosen的值，也可能是未被通过的值，具体原因可以自己推敲一下。
======
具体原因求告知一下下。。

**Comment by zhuwenzhuang** [comment]
@bh841128 
我的理解：
关键在于后面判断了nodeId 是否相同
OnProposerSendSuccess（ oPaxosMsg ）:
BallotNumber oBallot(oPaxosMsg.proposalid(), oPaxosMsg.nodeid());
if (m_poAcceptor->GetAcceptorState()->GetAcceptedBallot() != oBallot) 
  return;

如果同一个Proposer p1发送了一次Accept消息(instanceId =  1)，再发送了一次Propose 或者 Accept 消息 (instanceId =  2)，则：

1. Acceptor a2 此时可以认为 instanceId = 1 存在已经 chosen 的 value，只是本地 learner l2未收到ProposerSendSuccess消息。

2.如果Proposer p1的 proposalid 在消息(instanceId = 2)中没有增加，则说明第一次发送Accept消息没有遇到超时或者拒绝，则说明第一次Accept消息在Proposer端计数器达到了大多数。 

总的来说Proposer Accept消息的 NodeId ，instanceId，ProposalId 可以确定唯一的 Value 。

**Comment by bigheadzen** [comment]
[Issue 96](https://github.com/Tencent/phxpaxos/issues/96) 里说到了这个问题。

> 这是一个工程优化，通过 instance i+1 的消息顺带告知消息接收方 instance i 已经被 chosen，此时 instance i+1 （也就是acceptor的instanceid）并未chosen。

我的理解是为了尽可能的帮助 Acceptor 这边的 Instance 更快的迁移到下一个 Instance, 当前 instance i 的
 ProposerSendSuccess 消息可能由于一些原因没有到达。在 `Learner :: OnProposerSendSuccess` 里会检查 msg 的 ballot 和 当前 accepted ballot 是一致的，而新的消息instsance id 是 i + 1 则说明当前 instance i 已经被大多数通过了，当前 instance i 可以直接学习 accepted value, 然后迁移到下一个 instance。

**Comment by unixliang** [comment]
楼上两位说得对：）
