### ISSUE TITLE
使用phxpaxos实现某一group的数据迁移到新的机器

### ISSUE THREAD

**Issue by duhuanming** [Tencent/phxpaxos#91]
如果原有集群有100个group,每个group有负责一部分数据。如果想新增机器，接管原有集群中某一个group的数据，是否可以先把新集群的机器加入到现有集群进行复制，再分离出来？但是这个新的机群group id和原有机群一样，那么新机群就需要和旧集群有相同数量的group，但是新机群只需要一个group,这个问题如何解决？

**Comment by lynncui00** [comment]
目前还没有在线迁移的机制。
如果允许离线的话，可以修改数据目录下的g(group id)子目录名字。比如如果只需要一个group，则修改为g0，然后修改option的iGroupCount启动。
