### ISSUE TITLE
有没有考虑到会出现learn到一个值的同时，proposer也在做提交操作？

### ISSUE THREAD

**Issue by lichuang** [Tencent/phxpaxos#93]
int Instance :: ReceiveMsgForLearner(const PaxosMsg & oPaxosMsg)
{
if (m_oLearner.IsLearned())
    {
 
        
        {
            //this paxos instance end, tell proposal done
            m_oCommitCtx.SetResult(PaxosTryCommitRet_OK
                    , m_oLearner.GetInstanceID(), m_oLearner.GetLearnValue());

            if (m_iCommitTimerID > 0)
            {
                m_oIOLoop.RemoveTimer(m_iCommitTimerID);
            }
        }
}

这段代码里，islearn条件满足之后，就会setresult，如果正好proposer提交的instance ID和learnvalue都跟learn的值相同，这岂不是出错了？

**Comment by lichuang** [comment]
如果外部使用者的使用，就是在并发执行呢？毕竟提交一个值，是使用者说了算。

**Comment by unixliang** [comment]
提交一个值后，并不是马上执行proposer的逻辑，而是会排队，最终交由一个线程处理，所以不会有并发。

**Comment by lichuang** [comment]
考虑这样一个场景，节点A提交一个值，从代码里面来看，当提交成功的时候，A会广播一个proposesuccess的消息给集群中的其他节点，其他节点在接收处理了这个消息之后，才会调用instance：newinstance进行实例ID的变化。

问题在于，比如B节点，在还没有收到这个propose success消息之前，就自己提交了一个值，这种场景如何处理？这个场景，与你描述的单线程排队并没有冲突。

**Comment by lichuang** [comment]
考虑这样一个场景，节点A提交一个值，从代码里面来看，当提交成功的时候，A会广播一个proposesuccess的消息给集群中的其他节点，其他节点在接收处理了这个消息之后，才会调用instance：newinstance进行实例ID的变化。

问题在于，比如B节点，在还没有收到这个propose success消息之前，就自己提交了一个值，这个值的实例ID和值都跟前面A提交的一样，提交完毕以后，正好收到了process success消息，触发了islearn逻辑，认为B提交的这个值也成功了。

这种场景如何处理？这个场景，与你描述的单线程排队并没有冲突。

**Comment by lichuang** [comment]
另外，我看协议中在提交的时候有两个ID，一个是实例ID，一个是提交ID（proposal ID）。那么问题来了，实例ID在一次提交中是不会变化的，那么如何保证提交的时候这个实例ID就是当前可用的实例ID呢？

还是前面那个场景，节点A提交成功之后，假设占用了实例ID 100，在向其他节点propose success消息而节点B还没有收到该消息之前，节点B认为实例 ID100还是没有被占用的。

这种场景，又如何处理呢？

你可以说，就单个节点而言，其消息处理都是最后到一个线程中排队顺序处理，但是就集群而言，如何确保消息提交时实例ID不会乱序呢？

**Comment by unixliang** [comment]
> 问题在于，比如B节点，在还没有收到这个propose success消息之前，就自己提交了一个值，这个值的实例ID和值都跟前面A提交的一样，提交完毕以后，正好收到了process success消息，触发了islearn逻辑，认为B提交的这个值也成功了。

这种情况下，A和B对于同一个实例ID，提议的值是相同的，而且提交都成功了，这恰好就是一致的。
如果你想说，两次值一样的提交，最终只有一个传给了状态机，会不会相当于丢了一次状态转移？答案是不会。原因是：状态机需要使用方实现幂等，两个值一样的提议，在幂等的作用下，本来就只会产生一次有效的状态转移。所以，如果你希望两次提议都能生效，那他们的值是不会一样的。

**Comment by unixliang** [comment]
> 还是前面那个场景，节点A提交成功之后，假设占用了实例ID 100，在向其他节点广播propose success消息而节点B还没有收到该消息之前，节点B认为实例 ID100还是没有被占用的，此时如果节点B仍然以实例 100来提交一个值，岂不是会出问题？

如果B关于实例100提交的值和A提交的不同，那B会先对齐实例100的值为A提议的值，再重新提交原来想提议的值，这时候实例id至少是101了。

**Comment by lichuang** [comment]
我坚持认为，在m_oLearner.IsLearned()的情况下，需要进行一个判断，只有在确定learn到的值是本节点的提交时，才去调用commitctx.setresult，如果不做这个判断，会在多个节点同时提交值的情况下，某个节点误以为自己提交的值提交成功了。

**Comment by lynncui00** [comment]
@lichuang 
1. CommitCtx::SetResult 函数里面会检测这个值是否和Learner的值是否一致，如果不一致会返回相应的错误码。
2. 关于多个Proposor提交完全相同的值这种情况，由如下两种做法。
   a) 所有Propose操作都认为成功。
   b) 只有一个成功。
   以上两种做法没有对错之分。如PhxPaxos是一个要求幂等性的状态机转移的RSM结构，选择a)是更好的。而如果要选择b)，也只需要在Value头部添加一个UUID即可以做到。
