### ISSUE TITLE
Instance :: ReceiveMsgForAcceptor函数中为何要修改消息的实例ID？

### ISSUE THREAD

**Issue by lichuang** [Tencent/phxpaxos#96]
if (oPaxosMsg.instanceid() == m_oAcceptor.GetInstanceID() + 1)
    {
        //skip success message
        PaxosMsg oNewPaxosMsg = oPaxosMsg;
        oNewPaxosMsg.set_instanceid(m_oAcceptor.GetInstanceID());
        oNewPaxosMsg.set_msgtype(MsgType_PaxosLearner_ProposerSendSuccess);

        ReceiveMsgForLearner(oNewPaxosMsg);
    }

在这段代码中，此时收到的消息实例ID为当前acceptor实例ID+1，然后复制一份消息，修改该消息实例ID为acceptor的实例ID，发送propose send success消息出去。

我的疑问是，为什么这里要修改该消息的实例ID？或者，如果此时acceptor的实例ID已经被确认了，广播出去的消息，不是应该以当前acceptor的消息为准来创建吗？

**Comment by unixliang** [comment]
这是一个工程优化，通过 instance i+1 的消息顺带告知消息接收方 instance i 已经被 chosen，此时 instance i+1 （也就是acceptor的instanceid）并未chosen。

**Comment by lichuang** [comment]
问题在于，instance I和instance I+1的消息，可能并不一样啊，现在看代码的意思，是使用了i+1的消息体，而把这个消息体的实例ID设置成i，这样没有问题？

**Comment by unixliang** [comment]
你可以看看 ```Learner :: OnProposerSendSuccess```，里面确认的是消息接收方 Accepted instance i 的值，而不是将消息体里的值（instance i+1）确认为 instance i 的值，
