### ISSUE TITLE
为RTT较大的情况进行优化

### ISSUE THREAD

**Issue by zhuwenzhuang** [Tencent/phxpaxos#97]
一个Propose（or BatchPropose）会阻塞后续所有Propose调用Accept。
导致当Proposer和Acceptor之间RTT较大时，请求会被平均阻塞RTT/2的时间。
是否考虑使用“乐观Accept”，明确Accept消息之间依赖关系的情况下，提前发送后续Instance的Accept ？

**Comment by unixliang** [comment]
@zhuwenzhuang 指的应该是利用pipeline优化Proposer和Acceptor在跨域情况下的耗时。在这种情况下，即使使用了pipeline，单个提议成功所需耗时也至少是一个跨域RTT，这对client来说可能并不能接受，我们暂时未考虑该优化。
