### ISSUE TITLE
节点提交的值被踩掉的情况如何处理？

### ISSUE THREAD

**Issue by lichuang** [Tencent/phxpaxos#98]
考虑以下的场景，某集群中有A,B,C三个节点。

此时集群的实例ID为i，节点A提交值test成功，于是将会广播propose success给集群中的所有节点，而这个消息是run self first的，此时节点A自身收到这个消息，那么Instance :: ReceiveMsgForLearner这个函数中，就是islearned为true的情况，进而会调用函数setresult唤醒提交者，告知提交已经成功，且返回实例ID i。

但是，如果节点B，在收到A广播的propose success消息之前，自己提交了另一个值test b，因为没有收到propose success消息，所以B提交这个值的时候它自身的实例ID仍然是i，假设这里节点B最后提交成功，即A,B,C三个节点最终实例ID为i的值都是test b。

那么问题在于，前面A认为自己提交成功，并且返回给调用者提交成功的实例ID为i，这种错误的情况如何处理？

**Comment by unixliang** [comment]
> 但是，如果节点B，在收到A广播的propose success消息之前，自己提交了另一个值test b，因为没有收到propose success消息，所以B提交这个值的时候它自身的实例ID仍然是i，**假设这里节点B最后提交成功**，即A,B,C三个节点最终实例ID为i的值都是test b。

首先，instance i 值为 test 的提议已经chosen了，被chosen了的提议是已经确定且不会改变的，这与ABC三个节点是否已经处理propose success无关。
然后，节点B关于instance i 值为 test b 的提议不会通过，因为根据约束B3，其值会变更为test；节点B关于值为 test b 的提议可能会在 instance i+1 通过。

**Comment by lichuang** [comment]
从代码里面看并不是这样的。
被chosen之后，会发送propose success消息，只有在确认is learned的情况下，才会去调用instance::NewInstance 将acceptor、learner、proposer的instanceID递增。

如果没有递增实例ID，这是无法避免其他节点带着旧的实例ID来做投票，并且重新占用这个实例ID的，也就是前面提到的：节点B在收到propose success消息之前，以实例ID i再次发起了一次投票。

**Comment by unixliang** [comment]
这里分情况讨论：
1. 假设多数派未处理propose success，还在instance i，那么如上所述，根据节点B的提议的值会被约束B3修正；
2. 假设多数派已处理propose success，在Instance i+1，那么将没有多数派通过节点B的instance i
 的提议，因为 instance i+1 的节点会忽略 instance i 的 prepare/accept 消息（详见Instance :: ReceiveMsgForAcceptor）。

综上，节点B关于值为test b的提议不会在 instance i 通过。

**Comment by lichuang** [comment]
以Acceptor :: OnPrepare为例，它判断的条件是：

    BallotNumber oBallot(oPaxosMsg.proposalid(), oPaxosMsg.nodeid());

    if (oBallot >= m_oAcceptorState.GetPromiseBallot())
这种情况下可以接收prepare带过来的值。

那么问题就在于，如果节点B带上来的消息，其组成的ballot就是比原来节点A的ballot大呢，岂不是就会覆盖A的值了？

**Comment by unixliang** [comment]
你说的就是上面的第一种情况。
节点A作为Acceptor没有接受节点B提议的值，而是根据约束B3，通过PrepareReply（```oReplyPaxosMsg.set_value(m_oAcceptorState.GetAcceptedValue());```），修改了节点B提议的值。
这个值并不是ballot大的说了算，建议@lichuang重温paxos算法3个约束。
