### ISSUE TITLE
拼写问题

### ISSUE THREAD

**Issue by leonwu327** [Tencent/phxpaxos#99]
在WaitLock类中，这里用SetMaxWaitLogCount这个名字咋一看还没有看懂，应该SetMaxWaitLockCount吧

void WaitLock :: SetMaxWaitLogCount(const int iMaxWaitLockCount)
{
    m_iMaxWaitLockCount = iMaxWaitLockCount;
}

**Comment by unixliang** [comment]
感谢反馈，这里是拼错了。

**Comment by unixliang** [comment]
#125 fixed.
